version: "3"

services:
  #  mysqlservice:
  #    image: mysql:5.5
  #    ports:
  #      - 3307:3307
  #    container_name: mysql-container
  #    #    networks:
  #    #      - springcloud-movie-net
  #    network_mode: "host"
  #    hostname: localhost
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_USERNAME: root
  #      MYSQL_PASSWORD: root
  #      MYSQL_ALLOW_EMPTY_PASSWORD: "no"

  #  mongodbservice:
  #    image: mongo:latest
  #    container_name: mongo-container
  #    #    networks:
  #    #      - springcloud-movie-net
  #    network_mode: "host"
  #    hostname: localhost
  #    ports:
  #      - 27017:27017

  eureka-server:
    image: eureka-service
    build: eureka-server/
    container_name: eureka-server
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761


  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    #    depends_on:
    #      eureka-server:
    #        condition: service_healthy
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 8084:8084
  #    environment:
  #      API_GATEWAY_PORT: 808
  #      EUREKA_SERVER_IP: eureka-server                 #localhost
  #      EUREKA_SERVER_PORT: 8761

  product-webapp:
    build: product-webapp/
    image: product-webapp
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    container_name: product-webapp
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - "9020:9020"


  #  rabbitmq-container:
  #    image: rabbitmq:3-management
  #    ports:
  #      - 5672:5672
  #      - 15672:15672


  location-service:
    build: LocationService/
    container_name: location-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9092:9092
  #    environment:
  #      EUREKA_SERVER_IP: eureka-server                 #localhost
  #      EUREKA_SERVER_PORT: 8761
  #      SPRING_RABBITMQ_HOST: rabbitmq-container

  authentication-service:
    build: AuthenticationService/
    container_name: authentication-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9091:9091


  notification-service:
    build: NotificationService/
    container_name: notification-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9112:9112


  payment-service:
    build: PaymentService/
    container_name: payment-service
    depends_on:
      - api-gateway
      - eureka-server
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9093:9093
  #    environment:
  #      EUREKA_SERVER_IP: eureka-server
  #      EUREKA_SERVER_PORT: 8761


  review-service:
    build: ReviewService/
    container_name: review-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9094:9094
  #    environment:
  #      EUREKA_SERVER_IP: eureka-server
  #      EUREKA_SERVER_PORT: 8761

  ticket-booking-service:
    build: TicketBookingService/
    container_name: ticket-booking-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    network_mode: "host"
    hostname: localhost
    #    networks:
    #      - springcloud-movie-net
    ports:
      - 9095:9095
  #    environment:
  #      EUREKA_SERVER_IP: eureka-server                 #localhost
  #      EUREKA_SERVER_PORT: 8761


  user-service:
    build: UserService/
    container_name: user-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9096:9096
  #    environment:
  #      EUREKA_SERVER_IP: eureka-server                 #localhost
  #      EUREKA_SERVER_PORT: 8761
  #      SPRING_RABBITMQ_HOST: rabbitmq-container

  customer-care-service:
    build: CustomerCareService/
    container_name: customer-care-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    #    networks:
    #      - springcloud-movie-net
    network_mode: "host"
    hostname: localhost
    ports:
      - 9097:9097
#    environment:
#      EUREKA_SERVER_IP: eureka-server                 #localhost
#      EUREKA_SERVER_PORT: 8761


#networks:
#  springcloud-movie-net:
#    driver: bridge